### ISSUE TITLE
get_all_symbols.py

### ISSUE THREAD

**Issue by Airbum88** [abhipr1/StockForcastEngine#1]
Hello,

I've been getting this error when I run your script:

```
Traceback (most recent call last):
  File "/Users/eyschoi/PycharmProjects/StockProject/venv/test.py", line 157, in <module>
    f.serach_for_each_alphabet()
  File "/Users/eyschoi/PycharmProjects/StockProject/venv/test.py", line 122, in serach_for_each_alphabet
    self.get_total_sym_for_each_search(alphabet)
  File "/Users/eyschoi/PycharmProjects/StockProject/venv/test.py", line 104, in get_total_sym_for_each_search
    total_page_to_scan =  self.get_total_page_to_scan_for_alphabet(alphabet)
  File "/Users/eyschoi/PycharmProjects/StockProject/venv/test.py", line 88, in get_total_page_to_scan_for_alphabet
    total_search_qty = re.search('of ([1-9]*\,*[0-9]*).*',total_search_str).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Do you know why?

Thanks

**Comment by ximo1984** [comment]
Finance yahoo changed his html code and this scrap doesn't work.
